routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostCRUDController;
use App\Http\Controllers\MainCRUDController;
use App\Http\Controllers\UserAuthController;

Route::resource('/', MainCRUDController::class);


Route::post('/auth/save',[UserAuthController::class, 'save'])->name('auth.save');
Route::post('/auth/check',[UserAuthController::class, 'check'])->name('auth.check');
Route::get('/auth/logout',[UserAuthController::class, 'logout'])->name('auth.logout');




Route::group(['middleware'=>['AuthCheck']], function(){
    Route::get('/auth/login',[UserAuthController::class, 'login'])->name('auth.login');
    Route::get('/auth/register',[UserAuthController::class, 'register'])->name('auth.register');
    Route::resource('posts', PostCRUDController::class);

});

Route::get('/search','App\Http\Controllers\PostCRUDController@search');

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Admin extends Model
{
    use HasFactory;
}

app/Models/Post.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
class Post extends Model
{
    use HasFactory, Sortable;
  //  protected $fillable = [
  //      'title', 'groupa', 'scholar', 'hostel'];
    	public $sortable = ['id', 'title', 'groupa', 'rating', 'scholar', 'hostel'];

}

app/Models/User_test.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainCRUDController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class MainCRUDController extends Controller
{
    public function index()
    {
       $data['posts'] = Post::sortable()->paginate(5);
      return view('dashboard', $data);
    }

    public function search(Request $request)
    {
      $search = $request->get('search');
      $posts = \DB::table('posts')->where('title', 'like', '%'.$search.'%')->paginate(5);
      return view('posts/index', ['posts' => $posts]);
    }
    public function show(Post $post)
    {
        return view('posts.show',compact('post'));
    }


}

app/Http/Controllers/PostCRUDController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostCRUDController extends Controller
{


    public function index()
    {
       $data['posts'] = Post::sortable()->paginate(5);
      return view('posts.index', $data);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function search(Request $request)
    {
      $search = $request->get('search');
      $posts = \DB::table('posts')->where('title', 'like', '%'.$search.'%')->paginate(5);
      return view('posts/index', ['posts' => $posts]);
    }


    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
        ]);
        $path = $request->file('image')->store('public/images');
        $post = new Post;
        $post->title = $request->title;
        $post->image = $path;
        $post->groupa = $request->groupa;
        $post->rating = $request->rating;
        $post->hostel = $request->hostel;
        $post->scholar = $request->scholar;
        $post->save();

        return redirect()->route('posts.index')
                        ->with('success','Студент пройшов операцію');
    }

    public function show(Post $post)
    {
        return view('posts.show',compact('post'));
    }


    public function edit(Post $post)
    {
        return view('posts.edit',compact('post'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $post = Post::find($id);
        if($request->hasFile('image')){
            $request->validate([
              'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            ]);
            $path = $request->file('image')->store('public/images');
            $post->image = $path;
        }
        $post->title = $request->title;
        $post->groupa = $request->groupa;
        $post->hostel = $request->hostel;
        $post->rating = $request->rating;
        $post->scholar = $request->scholar;
        $post->save();

        return redirect()->route('posts.index')
                        ->with('success','Ого, воно працює: Операція успішна');
    }

    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index')
                        ->with('success','Военком буде рад новобранцям');
    }
}

app/Http/Controllers/UserAuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\Admin;

class UserAuthController extends Controller
{
  function login(){
         return view('auth.login');
     }
     function register(){
         return view('auth.register');
     }
     function save(Request $request){

         //валідація
         $request->validate([
             'name'=>'required',
             'email'=>'required|email|unique:admins',
             'password'=>'required|min:5|max:12'
         ]);

          //ввод даних в дб
          $admin = new Admin;
          $admin->name = $request->name;
          $admin->email = $request->email;
          $admin->password = Hash::make($request->password);
          $save = $admin->save();

          if($save){
             return back()->with('success','New User has been successfuly added to database');
          }else{
              return back()->with('fail','Something went wrong, try again later');
          }
     }

     function check(Request $request){
         //валідація
         $request->validate([
              'email'=>'required|email',
              'password'=>'required|min:5|max:12'
         ]);

         $userInfo = Admin::where('email','=', $request->email)->first();

         if(!$userInfo){
             return back()->with('fail','We do not recognize your email address');
         }else{
             //check password
             if(Hash::check($request->password, $userInfo->password)){
                 $request->session()->put('LoggedUser', $userInfo->id);
                 return redirect('posts');

             }else{
                 return back()->with('fail','Incorrect password');
             }
         }
     }

     function logout(){
         if(session()->has('LoggedUser')){
             session()->pull('LoggedUser');
             return redirect('/auth/login');
         }
     }

     function dashboard(){
         $data = ['LoggedUserInfo'=>Admin::where('id','=', session('LoggedUser'))->first()];
         return view('posts', $data);
     }

}

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Деканат</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
    #back {
  background-image: url(https://www.fg-a.com/wallpapers/white-background-retro-shapes.jpg);
  background-repeat: no-repeat;
   background-size: 1920px 1080px;
}

.zoom {
  transition: transform .2s;
}

.zoom:hover {
  transform: scale(1.5);
}
    </style>
</head>
<body id="back">
<div  class="container mt-2">
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Система Деканат</h2>
                <h3 style="font-size: 12px;">(Дісклеймер: всі збіги фото та фіо з реальними людьми - випадкові)</h3>
            </div>
            <div class="pull-right mb-1">
            </div>
        </div>
        <form style=" position: relative; left: 15px;"action="/search" method="get">
          <div class="input-group">
            <input type="search" name="search" class="form-control"
            <span  class="input-group-prepend">
              <button type="submit" class="btn btn-primary">Пошук</button>
            </span>
          </div>
        </form>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th width="20px">@sortablelink('id', 'id')</th>
            <th width="90px">Фото</th>
            <th>             @sortablelink('title', 'ФІО')</th>
            <th width="20px">@sortablelink('groupa', 'Група')</th>
            <th width="20px">@sortablelink('rating', 'Рейтинг')</th>
            <th width="20px">@sortablelink('hostel', 'Гуртожиток')</th>
            <th width="100px">@sortablelink('scholar', 'Стипендія')</th>
        </tr>
        @if($posts->count())
        @foreach ($posts as $post)
        @php
        $newh = preg_replace('/^0/', 'Немає', $post->hostel, 1);
        $news = preg_replace('/^0/', 'Немає', $post->scholar, 1);
        @endphp


        <tr>
            <td>{{ $post->id }}</td>
            <td><img class="zoom" src="{{ Storage::url($post->image) }}" height="80 " width="80" alt="" /></td>
            <td>{{ $post->title  }}</td>
            <td>{{ $post->groupa }}</td>
            <td>{{ $post->rating }}</td>
            <td>{{ $newh  }}</td>
            <td>{{ $news }}</td>
        </tr>
        @endforeach
        @endif
    </table>

          {!! $posts->appends(\Request::except('page'))->render() !!}

</body>
</html>

resources/views/posts/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Додавання</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
    #back {
  background-image: url(https://www.fg-a.com/wallpapers/white-background-retro-shapes.jpg);
  background-repeat: no-repeat;
   background-size: 1920px 1080px;
}
</style>
</head>
<body id="back">
<div class="container mt-2">

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left mb-2">
            <h2>Додати нового студента</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('posts.index') }}">Назад</a>
        </div>
    </div>
</div>

  @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
  @endif

<form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ФІО</strong>
                <input type="text" name="title" class="form-control" placeholder="Назва">
               @error('title')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Група</strong>
                <input type="text" name="groupa" class="form-control" placeholder="Номер">
               @error('title')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Рейтинг</strong>
                <input type="text" name="rating" class="form-control" placeholder="Кількість">
               @error('title')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Стипендія</strong>
                <input type="text" name="scholar" class="form-control" placeholder="Кількість">
               @error('title')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Гуртожиток</strong>
                <input type="text" name="hostel" class="form-control" placeholder="Номер">
               @error('title')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Post Image:</strong>
                 <input type="file" name="image" class="form-control" placeholder="Post Title">
                @error('image')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        <button type="submit" class="btn btn-primary ml-3">Підтвердити</button>
    </div>

</form>
</body>
</html>

resources/views/posts/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редагування</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
    #back {
  background-image: url(https://www.fg-a.com/wallpapers/white-background-retro-shapes.jpg);
  background-repeat: no-repeat;
   background-size: 1920px 1080px;
}
</style>
</head>
<body id="back">
<div class="container mt-2">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Редагування</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}" enctype="multipart/form-data">Назад</a>
            </div>
        </div>
    </div>

  @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
  @endif

    <form action="{{ route('posts.update',$post->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>ФІО студента</strong>
                    <input type="text" name="title" value="{{ $post->title }}" class="form-control" placeholder="ФІО">
                    @error('title')
                     <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Група</strong>
                        <input type="text" name="groupa" value="{{ $post->groupa }}" class="form-control" placeholder="ЛА-">
                        @error('title')
                         <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Стипендія</strong>
                    <input type="text" name="rating" value="{{ $post->rating }}" class="form-control" placeholder="Кількість">
                    @error('title')
                     <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
        </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Стипендія</strong>
                    <input type="text" name="scholar" value="{{ $post->scholar }}" class="form-control" placeholder="Кількість">
                    @error('title')
                     <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Гуртожиток</strong>
                    <input type="text" name="hostel" value="{{ $post->hostel }}" class="form-control" placeholder="Номер">
                    @error('title')
                     <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Фото</strong>
                 <input type="file" name="image" class="form-control" placeholder="Post Title">
                @error('image')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
            <div class="form-group">
                <img src="{{ Storage::url($post->image) }}" height="200" width="200" alt="" />
              </div>
          </div>
                <button type="submit" class="btn btn-primary ml-3">Відправити</button>

          </div>

      </form>
  </div>
</body>
</html>

resources/views/posts/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Деканат</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
    #back {
  background-image: url(https://www.fg-a.com/wallpapers/white-background-retro-shapes.jpg);
  background-repeat: no-repeat;
   background-size: 1920px 1080px;
}

.zoom {
  transition: transform .2s;
}

.zoom:hover {
  transform: scale(1.5);
}
    </style>
</head>
<body id="back">
<div  class="container mt-2">
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Система Деканат </h2>
                <a href="{{ route('auth.logout') }}">Закінчити сессію</a>
                <h3 style="font-size: 12px;">(Дісклеймер: всі збіги фото та фіо з реальними людьми - випадкові)</h3>
            </div>
            <div class="pull-right mb-1">
                <a class="btn btn-success" href="{{ route('posts.create') }}">Додати студента</a>
            </div>
        </div>
        <form style=" position: relative; left: 15px;"action="/search" method="get">
          <div class="input-group">
            <input type="search" name="search" class="form-control"
            <span  class="input-group-prepend">
              <button type="submit" class="btn btn-primary">Пошук</button>
            </span>
          </div>
        </form>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th width="20px">@sortablelink('id', 'id')</th>
            <th width="90px">Фото</th>
            <th>             @sortablelink('title', 'ФІО')</th>
            <th width="20px">@sortablelink('groupa', 'Група')</th>
            <th width="20px">@sortablelink('rating', 'Рейтинг')</th>
            <th width="20px">@sortablelink('hostel', 'Гуртожиток')</th>
            <th width="100px">@sortablelink('scholar', 'Стипендія')</th>
            <th width="240px">Дія</th>
        </tr>
        @if($posts->count())
        @foreach ($posts as $post)
        @php
        $newh = preg_replace('/^0/', 'Немає', $post->hostel, 1);
        $news = preg_replace('/^0/', 'Немає', $post->scholar, 1);
        @endphp


        <tr>
            <td>{{ $post->id }}</td>
            <td><img class="zoom" src="{{ Storage::url($post->image) }}" height="80 " width="80" alt="" /></td>
            <td>{{ $post->title  }}</td>
            <td>{{ $post->groupa }}</td>
            <td>{{ $post->rating }}</td>
            <td>{{ $newh  }}</td>
            <td>{{ $news }}</td>
            <td>
                <form action="{{ route('posts.destroy',$post->id) }}" method="POST">

                    <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Редагувати</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Видалити</button>
                </form>
            </td>
        </tr>
        @endforeach
        @endif
    </table>

        {!! $posts->appends(\Request::except('page'))->render() !!}

</body>
</html>